### PR TITLE
Add the packaging metadata to build the uport-wallet-cli snap

### PR DESCRIPTION
**Pull request by elopio**
This package will let you publish the latest uport-wallet-cli in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and Linux distributions. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.

### CODE REVIEW

**Comment by oed** [comment]
Hey, currently uport is only on a testnet. Not sure if we want this software to be public in the ubuntu store just yet. 
Also, is it common with cli tools in the ubuntu store?

**Comment by elopio** [comment]
Hello @oed! thanks for checking.

One of the ideas of build.snapcraft.io is to test early and often, and get feedback from your community of early adopters. Every change that lands in master will trigger a build and release to the edge channel in the store. You can put uport in there right now and give your contributors a super simple way to install and help you joining the testnet. They will get an automatic update for every new revision, so you will have more information to decide when your application is ready for a release. Once you are confident and move it to the stable channel in the store, it will appear on user searches so lots of new people will find it.

CLI tools are common, and I have a particular interest in decentralization. So I've been working with [parity](https://github.com/paritytech/parity#install-from-the-snap-store), [solidity](https://solidity.readthedocs.io/en/develop/installing-solidity.html#binary-packages), [blockstack](https://github.com/blockstack/blockstack-core/tree/master/images/community/snap), [ipfs](http://elopio.net/blog/ipfs-crowdtesting/) and some others. It would be great to also have uport in the store.

**Comment by oed** [comment]
Alright, sounds good. I just need to add a disclaimer that this is running tool is on a testnet before I merge. 
Took a closer look at snapcraft, seems very cool. Thanks for the PR :)

**Comment by oed** [comment]
Should be up and running now :)

**Comment by elopio** [comment]
This is great @oed! I've just installed it from the store without issues :)
Once the snap is in the store, we usually start a call for testing with the community:
https://forum.snapcraft.io/search?q=call%20for%20testing

It's great that the snap is ready on this project now, because you have the chance to engage super early adopters. If a call for testing sounds good to you, let me know if I can help there.

I will propose a PR for install instructions.

**Comment by oed** [comment]
Hey, at this point I don't really think we want to do a call for testing of this code. It's mostly just a tool to tests some functionallity of the uport app, as well as give devs an example of how to integrate uport.

**Pull request merged**
